FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 \
    python3-venv \
    python3-pip \
    python3-dev \
    python3-twisted \
    libssl-dev \
    libffi-dev \
    build-essential \
    git \
    net-tools \
    iproute2 \
    && rm -rf /var/lib/apt/lists/*


# Create cowrie user
RUN useradd -r -m -d /home/cowrie cowrie

WORKDIR /home/cowrie

# Copy Cowrie source (copied as root)
COPY cowrie /home/cowrie/cowrie

# Fix ownership so cowrie user can write
RUN chown -R cowrie:cowrie /home/cowrie/cowrie

# Switch to cowrie user
USER cowrie

ENV PATH="/home/cowrie/cowrie-env/bin:$PATH"

# Create venv INSIDE cowrie directory (matches docs)
RUN python3 -m venv cowrie/cowrie-env

RUN cowrie/cowrie-env/bin/pip install --upgrade pip && \
    cowrie/cowrie-env/bin/pip install -r cowrie/requirements.txt && \
    cowrie/cowrie-env/bin/pip install -e cowrie

EXPOSE 2222 2223

CMD ["cowrie/cowrie-env/bin/cowrie", "start"]
